cmake_minimum_required(VERSION 3.20)
project(nv2a_targets C)
enable_testing()
add_executable(nv2a_targets test_targets.c)
target_include_directories(nv2a_targets PRIVATE ../../src)
target_link_libraries(nv2a_targets PRIVATE d3d11 dxgi dxguid d3dcompiler)
foreach(samples 1 2 4 8)
    add_test(NAME nv2a_targets_${samples}x COMMAND nv2a_targets ${samples})
endforeach()
